### ISSUE TITLE
Dronebridge 0.6beta_img2 does not boot on Pi0 and PiA+ anymore

### ISSUE THREAD

**Issue by careyer** [DroneBridge/DroneBridge#32]
Hello Wolfgang,

just discovered that the 0.6beta image does not boot on Pi0 or PiA+ anymore. Guess this has something to do with the new kernel you are using?

Can you please check and correct this for the final version?
Thank you very much!

I also realized that the DroneBridge App 1.2.4 behaves somewhat strange and seems not to be 100% compatible. The RC channels show up for 1sec and then disappear... and then show up again... this repeats all of the time. Checked on two different Android devices (Pixel1 and Nexus7 Tablet). Same on both. Also writing the settings to the Air-Unit seems to have problems.

**Comment by htcohio** [comment]
Although I am not having trouble with the app itself, at least from my perspective everything kind of seems broken on 0.6. 

Although 0.6 it's not working very well for me at all with a pi 3 on the air side I tried it with a pi zero and single camera and I can also confirm that it does not boot.

I am continuing to use db 0.5  that has the modified image for the camera control.
