### ISSUE TITLE
Will this program be supported on openwrt in the future

### ISSUE THREAD

**Issue by lsy512** [DroneBridge/DroneBridge#53]
This is a good program.openwrt is a specialized routing system.Will this program be supported on openwrt in the future?

**Comment by Dronotique** [comment]
To follow... I vote also for this

**Comment by seeul8er** [comment]
OpenWRT is for routers etc. What use case would there be for DroneBridge? I barely have time to update the Android App for now. Supporting OpenWRT would be all the way down on my personal priority list. Sorry for that.

The software-based on the DB common lib should compile fine. It only uses very basic low level kernel functions like raw sockets and BPF.

**Comment by lsy512** [comment]
The router comes with WiFi, so many router modules can add a power amplifier to realize these functions

**Comment by Dronotique** [comment]
Routers also have RJ45 plugs. 

That could allow to have UAV <-> Wifi <-> OpenWRT <-> MultipleRJ45 <-> MultipleGCS

**Comment by seeul8er** [comment]
I see. Routers would make for a nice dedicated GND station. I agree with that. It would be worth giving a shot. 
However, I personally do not possess a spare OpenWrt capable router, so do not expect any development from my side right now.

**Comment by Dronotique** [comment]
I can advice the Xiaomi Mi Router 3G that give a good value for money

**Comment by seeul8er** [comment]
It ain't that easy. The router must have a wireless chip that supports monitor mode and packet injection. The packet injection rate should be rather high. That probably leaves us with routers that have simular chips that the currently supported wifi adapters.

**Comment by Dronotique** [comment]
OK. How I can know if the router wifi chip supports monitor mode and packet injection? Is there a linux command?

**Comment by seeul8er** [comment]
By searching the internet. Aircrack & WikiDevi offer some databases and checks on monitor mode and injection. It is all about the driver. OpenWRT also has to support that specific driver. So as you see ... no plug & play here :D
