### ISSUE TITLE
no .ini files found on SD-card found after flashing dronebridge 0.6.0

### ISSUE THREAD

**Issue by bpjdons** [DroneBridge/DroneBridge#54]

**Comment by seeul8er** [comment]
[Seems like a mounting and resizing problem.](https://gitter.im/DroneBridge/Lobby). Seems like some have already solved it. Maybe they can give a hint. I'll see when I find some time looking into it.

**Comment by bpjdons** [comment]
Hi Wolfgang,

 

Did you find a solution for this no .ini files not found?

 

 

 

 

 

Van: Wolfgang <notifications@github.com> 
Verzonden: Sunday, 3 May 2020 23:39
Aan: DroneBridge/DroneBridge <DroneBridge@noreply.github.com>
CC: bpjdons <bdons@xs4all.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [DroneBridge/DroneBridge] no .ini files found on SD-card found after flashing dronebridge 0.6.0 (#54)

 

Seems like a mounting and resizing problem. <https://gitter.im/DroneBridge/Lobby> . Seems like some have already solved it. Maybe they can give a hint. I'll see when I find some time looking into it.

**Comment by seeul8er** [comment]
Hi, sorry so much other stuff that I need to finish first.
Try the following: Identify the DroneBridge partition that is not mounting. It should be around 13GB in size. Format it to exFAT. Copy the config files etc. to the formatted partition (see attached files).

Could not test it but maybe that works.
[DB.zip](https://github.com/DroneBridge/DroneBridge/files/4618593/DB.zip)

**Comment by bpjdons** [comment]
Hi Wolfgang,

 

The program reports that there was no Wifi adapter found. I am using the Alpha longrange adapter.

This adapter works with Raspberri Pi 3b.

 

Also tried the TP-Link, that one was not recognized either (likewise with the PI 3b.

 

Thanks,

 

Van: Wolfgang <notifications@github.com> 
Verzonden: Tuesday, 12 May 2020 23:47
Aan: DroneBridge/DroneBridge <DroneBridge@noreply.github.com>
CC: bpjdons <bdons@xs4all.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [DroneBridge/DroneBridge] no .ini files found on SD-card found after flashing dronebridge 0.6.0 (#54)

 

Hi, sorry so much other stuff that I need to finish first.
Try the following: Identify the DroneBridge partition that is not mounting. It should be around 13GB in size. Format it to exFAT. Copy the config files etc. to the formatted partition (see attached files).

Could not test it but maybe that works.
DB.zip <https://github.com/DroneBridge/DroneBridge/files/4618593/DB.zip>

**Comment by bpjdons** [comment]
It works. I can see the program starting up till the point where it asked to login.

 

I have connected my Wifi adapters and configured the Rasperri PIs 3b.

 

I can not connect to the Wifi hotspot. (the same configuration works with Ez-wifibroadcast).

 

Please advise.

 

Thanks,

Bram

Van: Wolfgang <notifications@github.com> 
Verzonden: Tuesday, 12 May 2020 23:47
Aan: DroneBridge/DroneBridge <DroneBridge@noreply.github.com>
CC: bpjdons <bdons@xs4all.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [DroneBridge/DroneBridge] no .ini files found on SD-card found after flashing dronebridge 0.6.0 (#54)

 

Hi, sorry so much other stuff that I need to finish first.
Try the following: Identify the DroneBridge partition that is not mounting. It should be around 13GB in size. Format it to exFAT. Copy the config files etc. to the formatted partition (see attached files).

Could not test it but maybe that works.
DB.zip <https://github.com/DroneBridge/DroneBridge/files/4618593/DB.zip>

**Comment by seeul8er** [comment]
That is strange. Are you still on the stock image (except for the file system format maybe)? I cannot help you if you do not provide logs, but only a 'it does not work'.

Can you post the log you get by typing `journalctl -b` after you tried to connect to the access point?

**Comment by bpjdons** [comment]
OK, this is the situation now:

 

I do have a video connection with the PI groundstation (which is connected to the HDMI port).

 

At the point where the login prompt is shown I  tried to login with “pi’’ and ‘’raspberri’’.

The response is ‘’access denied”.

 

If you press ‘’alt + f10”’, you normally (with ez-wifibroadcast) gets you the setup screen in which you can enable ssh.

 

So I can’t sent you a log file. Still no access from my tablet via wifi to the ground PI.

 

Regards,

Bram

 

 

 

Van: Wolfgang <notifications@github.com> 
Verzonden: Tuesday, 19 May 2020 12:01
Aan: DroneBridge/DroneBridge <DroneBridge@noreply.github.com>
CC: bpjdons <bdons@xs4all.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [DroneBridge/DroneBridge] no .ini files found on SD-card found after flashing dronebridge 0.6.0 (#54)

 

That is strange. Are you still on the stock image (except for the file system format maybe)? I cannot help you if you do not provide logs, but only a 'it does not work'.

Can you post the log you get by typing journalctl -b after you tried to connect to the access point?

**Comment by seeul8er** [comment]
In DroneBridge there is only one screen. No need for ALT+Something.
Try to login using `raspberry`

**Comment by bpjdons** [comment]
Sorry, does not work either.

 

After displaying the login, it is difficult to login. The program most times just continues.

 

Van: Wolfgang <notifications@github.com> 
Verzonden: Tuesday, 19 May 2020 12:19
Aan: DroneBridge/DroneBridge <DroneBridge@noreply.github.com>
CC: bpjdons <bdons@xs4all.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [DroneBridge/DroneBridge] no .ini files found on SD-card found after flashing dronebridge 0.6.0 (#54)

 

In DroneBridge there is only one screen. No need for ALT+Something.
Try to login using raspberry

**Comment by seeul8er** [comment]
Connect the Pi via ethernet und just use SSH

**Comment by bpjdons** [comment]
I can not connect via ethernet because the PI did not obtain an IP address from my DHCP server.

 

With ez-wifibroadcast it gets an IP address of 192.168.178.47.

 

Van: Wolfgang <notifications@github.com> 
Verzonden: Wednesday, 20 May 2020 16:27
Aan: DroneBridge/DroneBridge <DroneBridge@noreply.github.com>
CC: bpjdons <bdons@xs4all.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [DroneBridge/DroneBridge] no .ini files found on SD-card found after flashing dronebridge 0.6.0 (#54)

 

Connect the Pi via ethernet und just use SSH

**Comment by mahmut20** [comment]
> Hi Wolfgang, Did you find a solution for this no .ini files not found?

maybe i can help you last time i got a issue that .ini did not apply. but i was changing wrong file.
i have a question which file are you trying to change?
