### ISSUE TITLE
Wlan stick not working properly in v0.6

### ISSUE THREAD

**Issue by Freshdouble** [DroneBridge/DroneBridge#60]
The wlan stick won't send any data in most of the cases in v0.6
It starts blinking so i assume that it is detected but stops blinking after a while and wont transmit any data, in v0.5-beta this stick works without any problems.

I'm using the wf-hp9201 wlan stick found on aliexpress with the AR9271 chipset.

**Software/Configuration:**
 - v0.6
 - Default Settings on Air and GND pi

**Hardware**
 - Raspberry Pi 3B
 - wf-hp9201 wlan stick on Air and GND pi

I also tried setting the MAC for the wlan stick in manual mode but without success. Most of the time the stick blinks shortly and stops blinking. Sometimes the stick blinks continuously and i can receive data at the groundstation. To get it working i have to constantly switch of and on the pis until the stick stays active.

In v0.5 beta the stick starts up the led on the stick is on and not blinking and i can receive data at the groundstation.

**Comment by seeul8er** [comment]
Can you provide the output of `dmesg` and `journalctl -u start_db.service` when it is not working?
