### ISSUE TITLE
Gstreamer pipeline

### ISSUE THREAD

**Issue by Freshdouble** [DroneBridge/DroneBridge#67]
I just wanted to ask what gstreamer pipeline is used to transmit the video and where this pipeline is defined on the AirPi and GroundPi.

Thank you in advance

**Comment by seeul8er** [comment]
No gstreamer used. We use the Pis video api directly through [raspivid](https://github.com/DroneBridge/DroneBridge/blob/1ccccabb8d4ea98e940a49e68dc23bc69752e523/startup/start_db_modules.py#L210) and the "[hello_video.bin](https://github.com/DroneBridge/DroneBridge/blob/1ccccabb8d4ea98e940a49e68dc23bc69752e523/startup/start_db_modules.py#L330)" player [implementation](https://github.com/DroneBridge/DroneBridge/tree/master/video/pi_video_player).
