### ISSUE TITLE
How do I set RPI to be AIR ?

### ISSUE THREAD

**Issue by GeorgeFlorian** [DroneBridge/DroneBridge#74]
I would like to know if I really need two RPI for this. Can't I use a normal Ground Control Sofware instead of an RPI ?

Also, how does the RPI know if it is Ground or Air ? Both settings are on the DB v0.7 image.
How do I configure it to be Air ?

The Getting Started guide doesn't explain much: https://dronebridge.gitbook.io/docs/dronebridge-for-raspberry-pi/getting-started#mavlink-based-flight-controller

It says `On the GndPi inside the OSD configuration file: #define MAVLINK` and `On the AirPi inside the[AIR] section:`
```
[AIR]
en_control=Y
serial_int_cont=/dev/serial1  # serial port connected to FC
baud_control=115200 # baud rate of UART/serial port
serial_prot=5  # for MAVLink transparent
pass_through_packet_size=64
```

These are both configured on the DB v0.7 image. Do I delete the ones that I don't need ? How does this work ?

Also, why do I need two RPIs ? All I want is something to send and receive Telemetry Data in MavLink format to and from an Ardupilot Flight Controller. I don't need camera or all the extras.

I am sorry, but the guide is very lacking.

**Comment by seeul8er** [comment]
#75
