### ISSUE TITLE
Is there a way to use the wifi adapter on my Linux computer without a ground pi station?

### ISSUE THREAD

**Issue by Jcwscience** [DroneBridge/DroneBridge#80]
Is there a way to receive the signal directly to my laptop from the air pi?

**Comment by seeul8er** [comment]
Sure. Just run the receiving scripts for telemetry, video etc. on your laptop. You will need drivers that support monitor mode but that is usually the case. Most likely the output power will be reduced compared to the Pi images

**Comment by Jcwscience** [comment]
Ahhh, ok sweet! I’m sure I can get the drivers.

**Comment by Jcwscience** [comment]
Although, looking at the project files I am a little confused as to what script to use. Should I use cmake to build the project first? Or just build the specific modules?
