### ISSUE TITLE
APK download "beta is expired"

### ISSUE THREAD

**Issue by mathijs28498** [DroneBridge/DroneBridge#82]
I tried using the apk via the download link in the readme, however this gave me an error saying that the "beta" is not used anymore and that I have to go to the github to download the latest version (which is this version).

I think the download link is to the wrong version of the apk (it is also called ..._2_0_2_beta_...).

**Comment by AiueoABC** [comment]
same here, did you find any solutions??

**Comment by seeul8er** [comment]
So sorry this took that long. I basically removed the expire function
https://drive.google.com/file/d/1AGMsrWHJvj8HxnZd_8HFgc7dvxMsE9hX/view?usp=sharing
